# Interacting With Arrays

In [1]:
import numpy as np

In [2]:
# A 2x5 array
a = np.array([ [1,2,3,4,5], [6,7,8,9,10] ])
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
# Accessing a row
a_r1 = a[0,:]
print('first row is:', a_r1)

In [ ]:
# Accessing a column
a_c2 = a[:,1]
print('second column is:', a_c2)

In [ ]:
# Accessing last element of first row
a_04 = a[0,4]
print('last element of first row is:',a_04)

In [ ]:
# Accessing an element w.r.t end of row or column
a_14 = a[-1,-1]  # -1 corresponds to last row/element.
a_03 = a[0, -2] # Similarly, -2 means second last row/column
print('element corresponding to last row and last column:', a_14)
print('element corresponding to first row and second last column:', a_03)

In [ ]:
# Accessing a range of elements (starting_idx:ending_idx+1)
a0_1_3 = a[0,1:4]
print('elements from first row, indices: 1 to 3:', a0_1_3)

In [ ]:
# Accessing alternate elements (starting_idx:ending_idx+1:step_size). For alternate elements, step_size=2 (pick every 2nd elem)
a_alternate = a[:, 0:5:2]
print('array with alternate columns are:', a_alternate)

In [ ]:
# Alternate elements with implicit starting, ending indices.
# If starting and ending indices are omitted, they are set to start and end of the list, respectively.
a_alternate_imp = a[:, ::2]
print('array with alternate columns are:', a_alternate_imp)


In [ ]:
# Editing an element
a_edit1 = a.copy()  # Creating a deep copy of a, so that when a_edit is changed, a remains unedited
a_edit1[0,-1] = 100
print('a after editing the last element of first row:', a_edit1)

In [ ]:
# Editing a range of elements
a_edit2 = a.copy()
a_edit2[:, 1] = 100
print('a after second column is assigned a value of 100:', a_edit2)
a_edit2[:, -2] = [200, 200]
print('a after second last column is assigned a value of 200:', a_edit2)

In [13]:
# Reshaping an array (Change of order)
# Only condition is that the reshaping order is chosen such that no. of elems in reshaped array = no. of elems in original array
b = np.array([1,2,3,4,5,6,7,8,9,10])
print('1D array is: \n', b)
c = b.reshape(2,5)
print('1D array reshaped to 2 rows and 5 columns is: \n', c)
d = np.array([ [1,2], [3,4], [5,6], [7,8], [9,10], [11,12] ])
print('2D array is: \n', d)
e = d.reshape(3,4)
print('2D array reshaped to 3 rows and 4 columns:\n',e)

1D array is: 
 [ 1  2  3  4  5  6  7  8  9 10]
1D array reshaped to 2 rows and 5 columns is: 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2D array is: 
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
2D array reshaped to 3 rows and 4 columns:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
