# Introducing 3D Arrays

In [1]:
import numpy as np

In [2]:
a = np.array([ [ [1,2,3], [4,5,6]  ], [ [7,8,9], [10,11,12] ]  ])
print('3d array with two 2d arrays with dimensions 2x3:')
a

3d array with two 2d arrays with dimensions 2x3:


array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [3]:
# Accessing element corresponding to first 2d array's first row and second column
a_001 = a[0,0,1]
print('element from first row and second column of first 2d array:', a_001)

element from first row and second column of first 2d array: 2


In [4]:
# Editing range of elements
a_edit1 = a.copy()
a_edit1[-1,-1,1:3] = [100,200]
print('a after the last two elements from the last row of last 2d array are edited:')
a_edit1

a after the last two elements from the last row of last 2d array are edited:


array([[[  1,   2,   3],
        [  4,   5,   6]],

       [[  7,   8,   9],
        [ 10, 100, 200]]])

In [6]:
# Accessing elements across 2d arrays
a__1 = a[:,:,1]
print('First columns from all 2d arrays')
a__1

First columns from all 2d arrays


array([[ 2,  5],
       [ 8, 11]])

In [7]:
# Editing elements across 2d arrays
a_edit2 = a.copy()
a_edit2[:,1,:] = [ [100,200,300], [400,500,600] ]
print('a after second rows from all 2d arrays are edited:')
a_edit2

a after second rows from all 2d arrays are edited:


array([[[  1,   2,   3],
        [100, 200, 300]],

       [[  7,   8,   9],
        [400, 500, 600]]])