# Populating Arrays With Pre-Defined Values


In [1]:
import numpy as np

In [2]:
# All zeros matrix
a = np.zeros( (2,3) )
print('All zeros matrix with 2 rows and 3 columns:')  #Default datatype: float64
a

All zeros matrix with 2 rows and 3 columns:


array([[0., 0., 0.],
       [0., 0., 0.]])

In [3]:
# All ones matrix
b = np.ones( (3,2), dtype='int8' )
print('All ones matrix with 3 rows and 2 columns and int8 as datatype:')
print(b)

All ones matrix with 3 rows and 2 columns and int8 as datatype:
[[1 1]
 [1 1]
 [1 1]]


In [4]:
# All custom number matrix
c = np.full((3,3), 100)  #Default dtype = int32
c

array([[100, 100, 100],
       [100, 100, 100],
       [100, 100, 100]])

In [5]:
# All custom number matrix with shape of some other matrix
d = np.full_like(a, 200, dtype='int32')
print('method 1 output:')
print(d)
e = np.full(a.shape,200)
print('method 2 output:')
print(e)

method 1 output:
[[200 200 200]
 [200 200 200]]
method 2 output:
[[200 200 200]
 [200 200 200]]


In [6]:
# Random decimal numbers (0-1) array
f = np.random.rand(4,5)
f

array([[0.30607131, 0.08860997, 0.49379904, 0.90789765, 0.53216633],
       [0.60890259, 0.17024481, 0.07901217, 0.533102  , 0.48871684],
       [0.41548247, 0.39290214, 0.83161588, 0.49770173, 0.76644734],
       [0.36329221, 0.95910516, 0.31236449, 0.06988467, 0.84442347]])

In [7]:
# Random decimal numbers (0-1) array with shape of other matrix
g = np.random.random_sample(a.shape)
g

array([[0.5146155 , 0.5171477 , 0.19171337],
       [0.38181709, 0.05832839, 0.30665805]])

In [8]:
# Random integer
h = np.random.randint(7)  # By default, lower limit is 0: Includes 0, excludes 7
print('Single non-negative random integer less than 7:', h)
i = np.random.randint(1,7)
print('Single positive random integer less than 7:', i)  #Includes 1, excludes 7
j = np.random.randint(-100,0, size=(5,5))
print('Array of dimensions 5x5 with random integers greater than equal to -100 and less than 0')
print(j)

Single non-negative random integer less than 7: 1
Single positive random integer less than 7: 3
Array of dimensions 5x5 with random integers greater than equal to -100 and less than 0
[[-72 -42 -97  -4 -88]
 [-67 -92 -36 -64 -94]
 [-65 -73 -16 -30 -43]
 [-44  -2 -58 -94 -67]
 [-83 -53  -3 -14 -82]]


In [9]:
# Identity matrix
k = np.identity(3)
k

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
# Range of numbers with int step [start:end)
# np.arange(start, end, step)
l = np.arange(5)  #Endpoint = 5, Default start = 0, step = 1
print('arange function in action with default starting point and step size: ')
print(l)
m = np.arange(1,11)
print('arange function in action with step size: ')
print(m)
n = np.arange(0,11,2)
print('arange function in action with starting point 0, ending point 11 and step size 2:')
print(n)

arange function in action with default starting point and step size: 
[0 1 2 3 4]
arange function in action with step size: 
[ 1  2  3  4  5  6  7  8  9 10]
arange function in action with starting point 0, ending point 11 and step size 2:
[ 0  2  4  6  8 10]


In [11]:
# Range of numbers with decimal step #
# np.linspace(start,stop,total_samples) (Default total_samples = 50)
# Step size can be calculated as: (stop-start)/(total_samples-1) (Note: both start and stop are included in the output)
o = np.linspace(1,50)
print('linspace function in action with default samples of 50:')
print(o)
p = np.linspace(0,1,100)
print('linspace function in action with 100 values ranging from 0 to 1:')
print(p)

linspace function in action with default samples of 50:
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35. 36.
 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49. 50.]
linspace function in action with 100 values ranging from 0 to 1:
[0.         0.01010101 0.02020202 0.03030303 0.04040404 0.05050505
 0.06060606 0.07070707 0.08080808 0.09090909 0.1010101  0.11111111
 0.12121212 0.13131313 0.14141414 0.15151515 0.16161616 0.17171717
 0.18181818 0.19191919 0.2020202  0.21212121 0.22222222 0.23232323
 0.24242424 0.25252525 0.26262626 0.27272727 0.28282828 0.29292929
 0.3030303  0.31313131 0.32323232 0.33333333 0.34343434 0.35353535
 0.36363636 0.37373737 0.38383838 0.39393939 0.4040404  0.41414141
 0.42424242 0.43434343 0.44444444 0.45454545 0.46464646 0.47474747
 0.48484848 0.49494949 0.50505051 0.51515152 0.52525253 0.53535354
 0.54545455 0.55555556 0.56565657 0.57575758 0.58585859 0.5959596
 0.606