# Matrix Multiplication

In [1]:
import numpy as np

In [2]:
a = np.array( [ [1,2], [3,4], [5,6] ] )
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [3]:
b = np.array( [ [7,8,9], [10,11,12] ] )
b

array([[ 7,  8,  9],
       [10, 11, 12]])

In [4]:
a_matmul_b = np.matmul(a,b)
print('a*b using matmul function is:\n', a_matmul_b, '\n')
a_dot_b = np.dot(a,b)
print('a*b using dot function is:\n', a_dot_b)

a*b using matmul function is:
 [[ 27  30  33]
 [ 61  68  75]
 [ 95 106 117]] 

a*b using dot function is:
 [[ 27  30  33]
 [ 61  68  75]
 [ 95 106 117]]
