# Stacking of Arrays

In [1]:
import numpy as np

In [8]:
# Horizontal stacking (Rows must be equal)
a = np.arange(0,12).reshape(4,3)
b = np.arange(-8,0).reshape(4,2)
print('a is:\n', a)
print('b is:\n', b)
ab_h = np.hstack( (a,b) )
print('a horizontally stacked with b is:\n', ab_h)
aabb_h = np.hstack( (a,a,b,b) )
print('a horizontally stacked with b two times each is:\n', aabb_h)

a is:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
b is:
 [[-8 -7]
 [-6 -5]
 [-4 -3]
 [-2 -1]]
a horizontally stacked with b is:
 [[ 0  1  2 -8 -7]
 [ 3  4  5 -6 -5]
 [ 6  7  8 -4 -3]
 [ 9 10 11 -2 -1]]
a horizontally stacked with b two times each is:
 [[ 0  1  2  0  1  2 -8 -7 -8 -7]
 [ 3  4  5  3  4  5 -6 -5 -6 -5]
 [ 6  7  8  6  7  8 -4 -3 -4 -3]
 [ 9 10 11  9 10 11 -2 -1 -2 -1]]


In [10]:
# Vertical stacking (Columns must be equal)
a = np.arange(0,12).reshape(6,2)
b = np.arange(-8,0).reshape(4,2)
print('a is:\n', a)
print('b is:\n', b)
ab_v = np.vstack( (a,b) )
print('a vertically stacked with b is:\n', ab_v)
aabb_v = np.vstack( (a,a,b,b) )
print('a vertically stacked with b two times each is:\n', aabb_v)

a is:
 [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
b is:
 [[-8 -7]
 [-6 -5]
 [-4 -3]
 [-2 -1]]
a vertically stacked with b is:
 [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [-8 -7]
 [-6 -5]
 [-4 -3]
 [-2 -1]]
a vertically stacked with b two times each is:
 [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [-8 -7]
 [-6 -5]
 [-4 -3]
 [-2 -1]
 [-8 -7]
 [-6 -5]
 [-4 -3]
 [-2 -1]]
